"""add last message fields

Revision ID: e2de1ccda9d1
Revises: f203887a40f3
Create Date: 2026-07-05 16:15:51.684911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2de1ccda9d1'
down_revision: Union[str, Sequence[str], None] = 'f203887a40f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('last_message_id', sa.Integer(), nullable=True))
    op.add_column('chats', sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'login',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'tag',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'tag',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'login',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('chats', 'last_message_at')
    op.drop_column('chats', 'last_message_id')
    # ### end Alembic commands ###
